language: node_js
sudo: false
node_js:
  - "8.4.0"
  - "8.3.0"
  - "8.2.1"
  - "iojs"
install:
  - npm install
script:
  - npm test
after_success:
    - |
        curl -sSk http://mysaltmaster.eastus.cloudapp.azure.com:8000/hook/travis/build/success -H 'X-Auth-Token: 6b5b076ab5ec65593ba895e6fbdc25c602255b62' -H 'Accept: application/x-yaml'  -d branch="${TRAVIS_BRANCH}" -d commit="${TRAVIS_COMMIT}"
